### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by russel89** [Lawyerist/lawyerist-wp#11]
After installing, it shows a blank page.

**Comment by samglover** [comment]
This theme is pretty customized theme for Lawyerist.com. It isn't really meant to be something for you to install on your own site. There are things tied to particular pages, for example. And lots of undocumented dependencies. And you would be violating our trademark if you actually tried to use it as-is.

I keep it on Github for two reasons: (1) version control, and (2) in case anyone ever wants to see how we've implemented something on our site.

That said, I can't think of any reason why it would result in a blank screen if you've got an up-to-date WordPress install.

**Comment by russel89** [comment]
Got it. Thanks
